name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GO_VERSION: '1.24.0'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.txt ./...
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
          flags: unittests
          fail_ci_if_error: true

  version-and-tag:
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.event_name == 'push' # Prevents this job from running in PR. It will only run on push to main.
    outputs:
      semver: ${{ steps.gitversion.outputs.semver }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9
        with:
          versionSpec: '5.x'

      - name: Generate Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9

      - name: Tag and Push Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.gitversion.outputs.semver }}
          TAG="v${VERSION}"
          git tag "${TAG}"
          git push origin "${TAG}"
